// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kziwtsjhgtyagprgsumw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6aXd0c2poZ3R5YWdwcmdzdW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDU2NjIsImV4cCI6MjA2ODU4MTY2Mn0.6CHALnv2tFHdTCv2BXjsZhaFme4R9-48LQJdUqOZhqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});